name: whatslink_generator
description: Lightweight Whatsapp Link Generator.

publish_to: 'none' 

version: 2.0.0+10

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
